name: flutter_application_1
description: "SD1 Audio Control App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_web_bluetooth: ^1.1.0  # or the latest you installed
  cupertino_icons: ^1.0.8

  # Native (Android/desktop) BLE
  flutter_reactive_ble: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
